# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
   dotnet add package Microsoft.ApplicationInsights --version 2.13.0 
   dotnet add package Microsoft.ApplicationInsights.AspNetCore --version 2.13.0
   dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--output $(build.artifactstagingdirectory)'
    workingDirectory: ./Allfiles/Labs/12/Starter/Api/
